export type { ApiError } from './ApiError.js';
export type { Document } from './Document.js';
export type { DocumentBlock } from './DocumentBlock.js';
export type { DocumentChunk } from './DocumentChunk.js';
export type { Evidence } from './Evidence.js';
export type { Fact } from './Fact.js';
export type { Health } from './Health.js';
export type { ProcessRequest } from './ProcessRequest.js';
export type { ProcessResponse } from './ProcessResponse.js';
export type { ProcessingIssue } from './ProcessingIssue.js';
export type { ProcessingJob } from './ProcessingJob.js';
export type { ProcessingStatus } from './ProcessingStatus.js';
export type { ReasonRequest } from './ReasonRequest.js';
export type { ReasonResponse } from './ReasonResponse.js';
export type { Relationship } from './Relationship.js';
export declare function validateContract(name: string, data: unknown): unknown;
